name:                spaceminer
version:             0.1.0.0
github:              "githubuser/spaceminer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spaceminer#readme>

dependencies:
# - ansi-terminal
- base
- bmp
- bytestring
- containers
- deepseq
- file-embed
- filepath
- integer-gmp
- safe
- text
- time
- unix
- vector
- vty

# extra
- extra
- monad-extras
- monad-loops

# formatting
- ormolu

# opengl and friends
- OpenGL
- JuicyPixels
- GLFW-b

# maybe game dev relevant
- pathfinding

# music generation
- Euterpea

default-extensions:
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PackageImports
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- ViewPatterns

library:
  source-dirs: lib

ghc-options: -O0 -j -Wall -Werror -optP-Wno-nonportable-include-path

executables:
  spaceminer:
    main: Main.hs
    source-dirs: exe
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: spaceminer

tests:
  spaceminer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: spaceminer
